defaultSemverRangePrefix: "~"

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_GITHUB_REGISTRY_TOKEN}

npmScopes:
  "mdedys":
    npmRegistryServer: https://npm.pkg.github.com
